# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/savins/pOptiPharm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/savins/pOptiPharm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/savins/pOptiPharm/CMakeFiles /home/savins/pOptiPharm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/savins/pOptiPharm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pOPShapeSimilarity

# Build rule for target.
pOPShapeSimilarity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pOPShapeSimilarity
.PHONY : pOPShapeSimilarity

# fast build rule for target.
pOPShapeSimilarity/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/build
.PHONY : pOPShapeSimilarity/fast

src/functions/Extras.o: src/functions/Extras.cpp.o
.PHONY : src/functions/Extras.o

# target to build an object file
src/functions/Extras.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Extras.cpp.o
.PHONY : src/functions/Extras.cpp.o

src/functions/Extras.i: src/functions/Extras.cpp.i
.PHONY : src/functions/Extras.i

# target to preprocess a source file
src/functions/Extras.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Extras.cpp.i
.PHONY : src/functions/Extras.cpp.i

src/functions/Extras.s: src/functions/Extras.cpp.s
.PHONY : src/functions/Extras.s

# target to generate assembly for a file
src/functions/Extras.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Extras.cpp.s
.PHONY : src/functions/Extras.cpp.s

src/functions/MoveAndRotate.o: src/functions/MoveAndRotate.cpp.o
.PHONY : src/functions/MoveAndRotate.o

# target to build an object file
src/functions/MoveAndRotate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/MoveAndRotate.cpp.o
.PHONY : src/functions/MoveAndRotate.cpp.o

src/functions/MoveAndRotate.i: src/functions/MoveAndRotate.cpp.i
.PHONY : src/functions/MoveAndRotate.i

# target to preprocess a source file
src/functions/MoveAndRotate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/MoveAndRotate.cpp.i
.PHONY : src/functions/MoveAndRotate.cpp.i

src/functions/MoveAndRotate.s: src/functions/MoveAndRotate.cpp.s
.PHONY : src/functions/MoveAndRotate.s

# target to generate assembly for a file
src/functions/MoveAndRotate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/MoveAndRotate.cpp.s
.PHONY : src/functions/MoveAndRotate.cpp.s

src/functions/Parameters.o: src/functions/Parameters.cpp.o
.PHONY : src/functions/Parameters.o

# target to build an object file
src/functions/Parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Parameters.cpp.o
.PHONY : src/functions/Parameters.cpp.o

src/functions/Parameters.i: src/functions/Parameters.cpp.i
.PHONY : src/functions/Parameters.i

# target to preprocess a source file
src/functions/Parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Parameters.cpp.i
.PHONY : src/functions/Parameters.cpp.i

src/functions/Parameters.s: src/functions/Parameters.cpp.s
.PHONY : src/functions/Parameters.s

# target to generate assembly for a file
src/functions/Parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Parameters.cpp.s
.PHONY : src/functions/Parameters.cpp.s

src/functions/Plot.o: src/functions/Plot.cpp.o
.PHONY : src/functions/Plot.o

# target to build an object file
src/functions/Plot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Plot.cpp.o
.PHONY : src/functions/Plot.cpp.o

src/functions/Plot.i: src/functions/Plot.cpp.i
.PHONY : src/functions/Plot.i

# target to preprocess a source file
src/functions/Plot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Plot.cpp.i
.PHONY : src/functions/Plot.cpp.i

src/functions/Plot.s: src/functions/Plot.cpp.s
.PHONY : src/functions/Plot.s

# target to generate assembly for a file
src/functions/Plot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Plot.cpp.s
.PHONY : src/functions/Plot.cpp.s

src/functions/Tanimoto.o: src/functions/Tanimoto.cpp.o
.PHONY : src/functions/Tanimoto.o

# target to build an object file
src/functions/Tanimoto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Tanimoto.cpp.o
.PHONY : src/functions/Tanimoto.cpp.o

src/functions/Tanimoto.i: src/functions/Tanimoto.cpp.i
.PHONY : src/functions/Tanimoto.i

# target to preprocess a source file
src/functions/Tanimoto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Tanimoto.cpp.i
.PHONY : src/functions/Tanimoto.cpp.i

src/functions/Tanimoto.s: src/functions/Tanimoto.cpp.s
.PHONY : src/functions/Tanimoto.s

# target to generate assembly for a file
src/functions/Tanimoto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/Tanimoto.cpp.s
.PHONY : src/functions/Tanimoto.cpp.s

src/functions/VolumeOverlap.o: src/functions/VolumeOverlap.cpp.o
.PHONY : src/functions/VolumeOverlap.o

# target to build an object file
src/functions/VolumeOverlap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/VolumeOverlap.cpp.o
.PHONY : src/functions/VolumeOverlap.cpp.o

src/functions/VolumeOverlap.i: src/functions/VolumeOverlap.cpp.i
.PHONY : src/functions/VolumeOverlap.i

# target to preprocess a source file
src/functions/VolumeOverlap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/VolumeOverlap.cpp.i
.PHONY : src/functions/VolumeOverlap.cpp.i

src/functions/VolumeOverlap.s: src/functions/VolumeOverlap.cpp.s
.PHONY : src/functions/VolumeOverlap.s

# target to generate assembly for a file
src/functions/VolumeOverlap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/VolumeOverlap.cpp.s
.PHONY : src/functions/VolumeOverlap.cpp.s

src/functions/pool.o: src/functions/pool.cpp.o
.PHONY : src/functions/pool.o

# target to build an object file
src/functions/pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/pool.cpp.o
.PHONY : src/functions/pool.cpp.o

src/functions/pool.i: src/functions/pool.cpp.i
.PHONY : src/functions/pool.i

# target to preprocess a source file
src/functions/pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/pool.cpp.i
.PHONY : src/functions/pool.cpp.i

src/functions/pool.s: src/functions/pool.cpp.s
.PHONY : src/functions/pool.s

# target to generate assembly for a file
src/functions/pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/pool.cpp.s
.PHONY : src/functions/pool.cpp.s

src/functions/sorting.o: src/functions/sorting.cpp.o
.PHONY : src/functions/sorting.o

# target to build an object file
src/functions/sorting.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/sorting.cpp.o
.PHONY : src/functions/sorting.cpp.o

src/functions/sorting.i: src/functions/sorting.cpp.i
.PHONY : src/functions/sorting.i

# target to preprocess a source file
src/functions/sorting.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/sorting.cpp.i
.PHONY : src/functions/sorting.cpp.i

src/functions/sorting.s: src/functions/sorting.cpp.s
.PHONY : src/functions/sorting.s

# target to generate assembly for a file
src/functions/sorting.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/functions/sorting.cpp.s
.PHONY : src/functions/sorting.cpp.s

src/model/Atom.o: src/model/Atom.cpp.o
.PHONY : src/model/Atom.o

# target to build an object file
src/model/Atom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Atom.cpp.o
.PHONY : src/model/Atom.cpp.o

src/model/Atom.i: src/model/Atom.cpp.i
.PHONY : src/model/Atom.i

# target to preprocess a source file
src/model/Atom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Atom.cpp.i
.PHONY : src/model/Atom.cpp.i

src/model/Atom.s: src/model/Atom.cpp.s
.PHONY : src/model/Atom.s

# target to generate assembly for a file
src/model/Atom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Atom.cpp.s
.PHONY : src/model/Atom.cpp.s

src/model/Bond.o: src/model/Bond.cpp.o
.PHONY : src/model/Bond.o

# target to build an object file
src/model/Bond.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Bond.cpp.o
.PHONY : src/model/Bond.cpp.o

src/model/Bond.i: src/model/Bond.cpp.i
.PHONY : src/model/Bond.i

# target to preprocess a source file
src/model/Bond.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Bond.cpp.i
.PHONY : src/model/Bond.cpp.i

src/model/Bond.s: src/model/Bond.cpp.s
.PHONY : src/model/Bond.s

# target to generate assembly for a file
src/model/Bond.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Bond.cpp.s
.PHONY : src/model/Bond.cpp.s

src/model/Box.o: src/model/Box.cpp.o
.PHONY : src/model/Box.o

# target to build an object file
src/model/Box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Box.cpp.o
.PHONY : src/model/Box.cpp.o

src/model/Box.i: src/model/Box.cpp.i
.PHONY : src/model/Box.i

# target to preprocess a source file
src/model/Box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Box.cpp.i
.PHONY : src/model/Box.cpp.i

src/model/Box.s: src/model/Box.cpp.s
.PHONY : src/model/Box.s

# target to generate assembly for a file
src/model/Box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Box.cpp.s
.PHONY : src/model/Box.cpp.s

src/model/Molecule.o: src/model/Molecule.cpp.o
.PHONY : src/model/Molecule.o

# target to build an object file
src/model/Molecule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Molecule.cpp.o
.PHONY : src/model/Molecule.cpp.o

src/model/Molecule.i: src/model/Molecule.cpp.i
.PHONY : src/model/Molecule.i

# target to preprocess a source file
src/model/Molecule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Molecule.cpp.i
.PHONY : src/model/Molecule.cpp.i

src/model/Molecule.s: src/model/Molecule.cpp.s
.PHONY : src/model/Molecule.s

# target to generate assembly for a file
src/model/Molecule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Molecule.cpp.s
.PHONY : src/model/Molecule.cpp.s

src/model/Point3DDouble.o: src/model/Point3DDouble.cpp.o
.PHONY : src/model/Point3DDouble.o

# target to build an object file
src/model/Point3DDouble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DDouble.cpp.o
.PHONY : src/model/Point3DDouble.cpp.o

src/model/Point3DDouble.i: src/model/Point3DDouble.cpp.i
.PHONY : src/model/Point3DDouble.i

# target to preprocess a source file
src/model/Point3DDouble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DDouble.cpp.i
.PHONY : src/model/Point3DDouble.cpp.i

src/model/Point3DDouble.s: src/model/Point3DDouble.cpp.s
.PHONY : src/model/Point3DDouble.s

# target to generate assembly for a file
src/model/Point3DDouble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DDouble.cpp.s
.PHONY : src/model/Point3DDouble.cpp.s

src/model/Point3DInteger.o: src/model/Point3DInteger.cpp.o
.PHONY : src/model/Point3DInteger.o

# target to build an object file
src/model/Point3DInteger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DInteger.cpp.o
.PHONY : src/model/Point3DInteger.cpp.o

src/model/Point3DInteger.i: src/model/Point3DInteger.cpp.i
.PHONY : src/model/Point3DInteger.i

# target to preprocess a source file
src/model/Point3DInteger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DInteger.cpp.i
.PHONY : src/model/Point3DInteger.cpp.i

src/model/Point3DInteger.s: src/model/Point3DInteger.cpp.s
.PHONY : src/model/Point3DInteger.s

# target to generate assembly for a file
src/model/Point3DInteger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Point3DInteger.cpp.s
.PHONY : src/model/Point3DInteger.cpp.s

src/model/Quaternion.o: src/model/Quaternion.cpp.o
.PHONY : src/model/Quaternion.o

# target to build an object file
src/model/Quaternion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Quaternion.cpp.o
.PHONY : src/model/Quaternion.cpp.o

src/model/Quaternion.i: src/model/Quaternion.cpp.i
.PHONY : src/model/Quaternion.i

# target to preprocess a source file
src/model/Quaternion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Quaternion.cpp.i
.PHONY : src/model/Quaternion.cpp.i

src/model/Quaternion.s: src/model/Quaternion.cpp.s
.PHONY : src/model/Quaternion.s

# target to generate assembly for a file
src/model/Quaternion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/model/Quaternion.cpp.s
.PHONY : src/model/Quaternion.cpp.s

src/read_write/ReadMolecule.o: src/read_write/ReadMolecule.cpp.o
.PHONY : src/read_write/ReadMolecule.o

# target to build an object file
src/read_write/ReadMolecule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMolecule.cpp.o
.PHONY : src/read_write/ReadMolecule.cpp.o

src/read_write/ReadMolecule.i: src/read_write/ReadMolecule.cpp.i
.PHONY : src/read_write/ReadMolecule.i

# target to preprocess a source file
src/read_write/ReadMolecule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMolecule.cpp.i
.PHONY : src/read_write/ReadMolecule.cpp.i

src/read_write/ReadMolecule.s: src/read_write/ReadMolecule.cpp.s
.PHONY : src/read_write/ReadMolecule.s

# target to generate assembly for a file
src/read_write/ReadMolecule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMolecule.cpp.s
.PHONY : src/read_write/ReadMolecule.cpp.s

src/read_write/ReadMoleculeSD.o: src/read_write/ReadMoleculeSD.cpp.o
.PHONY : src/read_write/ReadMoleculeSD.o

# target to build an object file
src/read_write/ReadMoleculeSD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMoleculeSD.cpp.o
.PHONY : src/read_write/ReadMoleculeSD.cpp.o

src/read_write/ReadMoleculeSD.i: src/read_write/ReadMoleculeSD.cpp.i
.PHONY : src/read_write/ReadMoleculeSD.i

# target to preprocess a source file
src/read_write/ReadMoleculeSD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMoleculeSD.cpp.i
.PHONY : src/read_write/ReadMoleculeSD.cpp.i

src/read_write/ReadMoleculeSD.s: src/read_write/ReadMoleculeSD.cpp.s
.PHONY : src/read_write/ReadMoleculeSD.s

# target to generate assembly for a file
src/read_write/ReadMoleculeSD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/ReadMoleculeSD.cpp.s
.PHONY : src/read_write/ReadMoleculeSD.cpp.s

src/read_write/WriteMolecule.o: src/read_write/WriteMolecule.cpp.o
.PHONY : src/read_write/WriteMolecule.o

# target to build an object file
src/read_write/WriteMolecule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/WriteMolecule.cpp.o
.PHONY : src/read_write/WriteMolecule.cpp.o

src/read_write/WriteMolecule.i: src/read_write/WriteMolecule.cpp.i
.PHONY : src/read_write/WriteMolecule.i

# target to preprocess a source file
src/read_write/WriteMolecule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/WriteMolecule.cpp.i
.PHONY : src/read_write/WriteMolecule.cpp.i

src/read_write/WriteMolecule.s: src/read_write/WriteMolecule.cpp.s
.PHONY : src/read_write/WriteMolecule.s

# target to generate assembly for a file
src/read_write/WriteMolecule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/read_write/WriteMolecule.cpp.s
.PHONY : src/read_write/WriteMolecule.cpp.s

src/uego/ini.o: src/uego/ini.cc.o
.PHONY : src/uego/ini.o

# target to build an object file
src/uego/ini.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/ini.cc.o
.PHONY : src/uego/ini.cc.o

src/uego/ini.i: src/uego/ini.cc.i
.PHONY : src/uego/ini.i

# target to preprocess a source file
src/uego/ini.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/ini.cc.i
.PHONY : src/uego/ini.cc.i

src/uego/ini.s: src/uego/ini.cc.s
.PHONY : src/uego/ini.s

# target to generate assembly for a file
src/uego/ini.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/ini.cc.s
.PHONY : src/uego/ini.cc.s

src/uego/master.o: src/uego/master.cc.o
.PHONY : src/uego/master.o

# target to build an object file
src/uego/master.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/master.cc.o
.PHONY : src/uego/master.cc.o

src/uego/master.i: src/uego/master.cc.i
.PHONY : src/uego/master.i

# target to preprocess a source file
src/uego/master.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/master.cc.i
.PHONY : src/uego/master.cc.i

src/uego/master.s: src/uego/master.cc.s
.PHONY : src/uego/master.s

# target to generate assembly for a file
src/uego/master.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/master.cc.s
.PHONY : src/uego/master.cc.s

src/uego/nmol.o: src/uego/nmol.cc.o
.PHONY : src/uego/nmol.o

# target to build an object file
src/uego/nmol.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/nmol.cc.o
.PHONY : src/uego/nmol.cc.o

src/uego/nmol.i: src/uego/nmol.cc.i
.PHONY : src/uego/nmol.i

# target to preprocess a source file
src/uego/nmol.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/nmol.cc.i
.PHONY : src/uego/nmol.cc.i

src/uego/nmol.s: src/uego/nmol.cc.s
.PHONY : src/uego/nmol.s

# target to generate assembly for a file
src/uego/nmol.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/nmol.cc.s
.PHONY : src/uego/nmol.cc.s

src/uego/project/molvalSS.o: src/uego/project/molvalSS.cc.o
.PHONY : src/uego/project/molvalSS.o

# target to build an object file
src/uego/project/molvalSS.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/molvalSS.cc.o
.PHONY : src/uego/project/molvalSS.cc.o

src/uego/project/molvalSS.i: src/uego/project/molvalSS.cc.i
.PHONY : src/uego/project/molvalSS.i

# target to preprocess a source file
src/uego/project/molvalSS.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/molvalSS.cc.i
.PHONY : src/uego/project/molvalSS.cc.i

src/uego/project/molvalSS.s: src/uego/project/molvalSS.cc.s
.PHONY : src/uego/project/molvalSS.s

# target to generate assembly for a file
src/uego/project/molvalSS.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/molvalSS.cc.s
.PHONY : src/uego/project/molvalSS.cc.s

src/uego/project/nrealopt.o: src/uego/project/nrealopt.cc.o
.PHONY : src/uego/project/nrealopt.o

# target to build an object file
src/uego/project/nrealopt.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/nrealopt.cc.o
.PHONY : src/uego/project/nrealopt.cc.o

src/uego/project/nrealopt.i: src/uego/project/nrealopt.cc.i
.PHONY : src/uego/project/nrealopt.i

# target to preprocess a source file
src/uego/project/nrealopt.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/nrealopt.cc.i
.PHONY : src/uego/project/nrealopt.cc.i

src/uego/project/nrealopt.s: src/uego/project/nrealopt.cc.s
.PHONY : src/uego/project/nrealopt.s

# target to generate assembly for a file
src/uego/project/nrealopt.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/project/nrealopt.cc.s
.PHONY : src/uego/project/nrealopt.cc.s

src/uego/speclist.o: src/uego/speclist.cc.o
.PHONY : src/uego/speclist.o

# target to build an object file
src/uego/speclist.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/speclist.cc.o
.PHONY : src/uego/speclist.cc.o

src/uego/speclist.i: src/uego/speclist.cc.i
.PHONY : src/uego/speclist.i

# target to preprocess a source file
src/uego/speclist.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/speclist.cc.i
.PHONY : src/uego/speclist.cc.i

src/uego/speclist.s: src/uego/speclist.cc.s
.PHONY : src/uego/speclist.s

# target to generate assembly for a file
src/uego/speclist.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/speclist.cc.s
.PHONY : src/uego/speclist.cc.s

src/uego/sspopt.o: src/uego/sspopt.cc.o
.PHONY : src/uego/sspopt.o

# target to build an object file
src/uego/sspopt.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/sspopt.cc.o
.PHONY : src/uego/sspopt.cc.o

src/uego/sspopt.i: src/uego/sspopt.cc.i
.PHONY : src/uego/sspopt.i

# target to preprocess a source file
src/uego/sspopt.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/sspopt.cc.i
.PHONY : src/uego/sspopt.cc.i

src/uego/sspopt.s: src/uego/sspopt.cc.s
.PHONY : src/uego/sspopt.s

# target to generate assembly for a file
src/uego/sspopt.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/sspopt.cc.s
.PHONY : src/uego/sspopt.cc.s

src/uego/usrintf/configur.o: src/uego/usrintf/configur.cc.o
.PHONY : src/uego/usrintf/configur.o

# target to build an object file
src/uego/usrintf/configur.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/configur.cc.o
.PHONY : src/uego/usrintf/configur.cc.o

src/uego/usrintf/configur.i: src/uego/usrintf/configur.cc.i
.PHONY : src/uego/usrintf/configur.i

# target to preprocess a source file
src/uego/usrintf/configur.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/configur.cc.i
.PHONY : src/uego/usrintf/configur.cc.i

src/uego/usrintf/configur.s: src/uego/usrintf/configur.cc.s
.PHONY : src/uego/usrintf/configur.s

# target to generate assembly for a file
src/uego/usrintf/configur.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/configur.cc.s
.PHONY : src/uego/usrintf/configur.cc.s

src/uego/usrintf/main.o: src/uego/usrintf/main.cc.o
.PHONY : src/uego/usrintf/main.o

# target to build an object file
src/uego/usrintf/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/main.cc.o
.PHONY : src/uego/usrintf/main.cc.o

src/uego/usrintf/main.i: src/uego/usrintf/main.cc.i
.PHONY : src/uego/usrintf/main.i

# target to preprocess a source file
src/uego/usrintf/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/main.cc.i
.PHONY : src/uego/usrintf/main.cc.i

src/uego/usrintf/main.s: src/uego/usrintf/main.cc.s
.PHONY : src/uego/usrintf/main.s

# target to generate assembly for a file
src/uego/usrintf/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/main.cc.s
.PHONY : src/uego/usrintf/main.cc.s

src/uego/usrintf/msgintf.o: src/uego/usrintf/msgintf.cc.o
.PHONY : src/uego/usrintf/msgintf.o

# target to build an object file
src/uego/usrintf/msgintf.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/msgintf.cc.o
.PHONY : src/uego/usrintf/msgintf.cc.o

src/uego/usrintf/msgintf.i: src/uego/usrintf/msgintf.cc.i
.PHONY : src/uego/usrintf/msgintf.i

# target to preprocess a source file
src/uego/usrintf/msgintf.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/msgintf.cc.i
.PHONY : src/uego/usrintf/msgintf.cc.i

src/uego/usrintf/msgintf.s: src/uego/usrintf/msgintf.cc.s
.PHONY : src/uego/usrintf/msgintf.s

# target to generate assembly for a file
src/uego/usrintf/msgintf.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pOPShapeSimilarity.dir/build.make CMakeFiles/pOPShapeSimilarity.dir/src/uego/usrintf/msgintf.cc.s
.PHONY : src/uego/usrintf/msgintf.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pOPShapeSimilarity"
	@echo "... src/functions/Extras.o"
	@echo "... src/functions/Extras.i"
	@echo "... src/functions/Extras.s"
	@echo "... src/functions/MoveAndRotate.o"
	@echo "... src/functions/MoveAndRotate.i"
	@echo "... src/functions/MoveAndRotate.s"
	@echo "... src/functions/Parameters.o"
	@echo "... src/functions/Parameters.i"
	@echo "... src/functions/Parameters.s"
	@echo "... src/functions/Plot.o"
	@echo "... src/functions/Plot.i"
	@echo "... src/functions/Plot.s"
	@echo "... src/functions/Tanimoto.o"
	@echo "... src/functions/Tanimoto.i"
	@echo "... src/functions/Tanimoto.s"
	@echo "... src/functions/VolumeOverlap.o"
	@echo "... src/functions/VolumeOverlap.i"
	@echo "... src/functions/VolumeOverlap.s"
	@echo "... src/functions/pool.o"
	@echo "... src/functions/pool.i"
	@echo "... src/functions/pool.s"
	@echo "... src/functions/sorting.o"
	@echo "... src/functions/sorting.i"
	@echo "... src/functions/sorting.s"
	@echo "... src/model/Atom.o"
	@echo "... src/model/Atom.i"
	@echo "... src/model/Atom.s"
	@echo "... src/model/Bond.o"
	@echo "... src/model/Bond.i"
	@echo "... src/model/Bond.s"
	@echo "... src/model/Box.o"
	@echo "... src/model/Box.i"
	@echo "... src/model/Box.s"
	@echo "... src/model/Molecule.o"
	@echo "... src/model/Molecule.i"
	@echo "... src/model/Molecule.s"
	@echo "... src/model/Point3DDouble.o"
	@echo "... src/model/Point3DDouble.i"
	@echo "... src/model/Point3DDouble.s"
	@echo "... src/model/Point3DInteger.o"
	@echo "... src/model/Point3DInteger.i"
	@echo "... src/model/Point3DInteger.s"
	@echo "... src/model/Quaternion.o"
	@echo "... src/model/Quaternion.i"
	@echo "... src/model/Quaternion.s"
	@echo "... src/read_write/ReadMolecule.o"
	@echo "... src/read_write/ReadMolecule.i"
	@echo "... src/read_write/ReadMolecule.s"
	@echo "... src/read_write/ReadMoleculeSD.o"
	@echo "... src/read_write/ReadMoleculeSD.i"
	@echo "... src/read_write/ReadMoleculeSD.s"
	@echo "... src/read_write/WriteMolecule.o"
	@echo "... src/read_write/WriteMolecule.i"
	@echo "... src/read_write/WriteMolecule.s"
	@echo "... src/uego/ini.o"
	@echo "... src/uego/ini.i"
	@echo "... src/uego/ini.s"
	@echo "... src/uego/master.o"
	@echo "... src/uego/master.i"
	@echo "... src/uego/master.s"
	@echo "... src/uego/nmol.o"
	@echo "... src/uego/nmol.i"
	@echo "... src/uego/nmol.s"
	@echo "... src/uego/project/molvalSS.o"
	@echo "... src/uego/project/molvalSS.i"
	@echo "... src/uego/project/molvalSS.s"
	@echo "... src/uego/project/nrealopt.o"
	@echo "... src/uego/project/nrealopt.i"
	@echo "... src/uego/project/nrealopt.s"
	@echo "... src/uego/speclist.o"
	@echo "... src/uego/speclist.i"
	@echo "... src/uego/speclist.s"
	@echo "... src/uego/sspopt.o"
	@echo "... src/uego/sspopt.i"
	@echo "... src/uego/sspopt.s"
	@echo "... src/uego/usrintf/configur.o"
	@echo "... src/uego/usrintf/configur.i"
	@echo "... src/uego/usrintf/configur.s"
	@echo "... src/uego/usrintf/main.o"
	@echo "... src/uego/usrintf/main.i"
	@echo "... src/uego/usrintf/main.s"
	@echo "... src/uego/usrintf/msgintf.o"
	@echo "... src/uego/usrintf/msgintf.i"
	@echo "... src/uego/usrintf/msgintf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

